# Generated by Django 4.0.1 on 2022-11-27 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_blog_post_rename_topic_blog_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='participants',
            field=models.ManyToManyField(blank='True', null='True', related_name='visitors', to=settings.AUTH_USER_MODEL),
        ),
    ]
